Repository ChromeGaming/Physi-c-Tech, pull requests merged in 2024-05, with the labels that each got.

#14 Create a new style.css file
  index.html
  style.css
Labels: enhancement, GSSoC'24, Level - 2

#70 Fixed #61
  style.css
Labels: gssoc, level1

#74 Added CONTRIBUTING.md
  Contributing.md
Labels: gssoc, level1

#46 Fixed Issue #34
  game.js
  index.html
Labels: gssoc, level1

#85 Scroll bar design is updated
  style.css
Labels: gssoc, level1

#95 [New Feature]: Would like to add preloader?
  index.html
Labels: gssoc, level1

#103 [New Feature]: Enhancement the Popup Message
  description.js
  index.html
  style.css
Labels: gssoc, level2

#102 Fixed Issue- #22 : Improving buttons
  index.html
  style.css
Labels: gssoc, level2

#117 Enhanced Landing page buttons before and after UI experience
  style.css
Labels: gssoc, level1

#87 adding a background picture that suits the website game theme
  bg.jpg
  index.html
  style.css
Labels: Need changes, gssoc, Under Review

#123 FIXED Issue #110 : Added Feedback Form
  feedback.css
  feedback.html
  index.html
  preloader.js
  style.css
Labels: gssoc, level3

#127 added space between text and image in about.html
  about.html
Labels: enhancement, gssoc, level1

#140 Navigation Button Added #109
  about.html
  index.html
Labels: enhancement, gssoc, level2
