Repository ChromeGaming/Physi-c-Tech, pull requests merged in 2024-06, with the labels that each got.

#165 fix-#150: Git conflict text in website
  index.html
Labels: gssoc, level1

#175 Enhancing Feedback form (Issue #162)
  feedback.html
Labels: gssoc, level1

#178 Making Responsive #167
  about.html
Labels: gssoc, level3

#181 made home page responsive
  index.html
  style.css
Labels: gssoc, level1

#187 Improve README: Guidelines & Description
  README.md
Labels: gssoc, level1

#183 Fixes #144 : Modified About Page
  about.html
Labels: gssoc, level1

#191 Scroll and other changes
  1.png
  about.html
  style.css
Labels: gssoc, level1

#198 add docker-file
  Dockerfile
Labels: gssoc, level1

#207 Scroll Down Issue fixed
  about.html
  style.css
Labels: gssoc, level1

#217 REORGANISED all the files into different folders
  about.html
  css/feedback.css
  css/style.css
  feedback.html
  images/1.png
  images/2.png
  images/3.png
  images/4.png
  images/5.png
  images/atom.png
  images/scientist.png
  index.html
  js/description.js
  js/elements.js
  js/game.js
  js/index.js
  js/music.js
  js/preloader.js
  js/svg.js
  json/package-lock.json
Labels: gssoc, level2

#225 Conformation pop-up and navigation to feedback fixed
  css/feedback.css
  css/style.css
  feedback.html
  index.html
  js/feedback.js
Labels: gssoc, level2

#227 change cursor design
  about.html
  css/feedback.css
  css/style.css
  images/CURSOR1.png
Labels: gssoc, level1
